[package]
name = "calc"
version = "0.1.2"
edition = "2024"

[dependencies]
iced = "0.13.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
time = { version = "0.3.41", features = ["serde"] }
